/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-northeast-1",
    "aws_cloud_logic_custom": [
        {
            "name": "votingApiGateway",
            "endpoint": "https://co1uep28ze.execute-api.ap-northeast-1.amazonaws.com/dev",
            "region": "ap-northeast-1"
        }
    ],
    "aws_dynamodb_all_tables_region": "ap-northeast-1",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "Speaker-dev",
            "region": "ap-northeast-1"
        },
        {
            "tableName": "SpeakerList-dev",
            "region": "ap-northeast-1"
        },
        {
            "tableName": "Event-dev",
            "region": "ap-northeast-1"
        },
        {
            "tableName": "Evaluation-dev",
            "region": "ap-northeast-1"
        },
        {
            "tableName": "User-dev",
            "region": "ap-northeast-1"
        }
    ]
};


export default awsmobile;
